---
networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge
services:
  backend:
    depends_on:
      - postgres
    image: george051191/nestjsapp
    links:
      - postgres
    networks:
      - internal-network
      - internet
    ports:
      - '4000:3000'
    restart: on-failure
  front:
    depends_on:
      - backend
    image: george051191/appfront
    ports:
      - '8081:80'
    restart: on-failure
  postgres:
    env_file:
      - .env
    image: postgres
    networks:
      - internal-network
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - data:${POSTGRES_PGDATA}
volumes:
    data:    
version: '3.9'